# Generated by Django 3.2.7 on 2021-11-15 14:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiaryText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('coordinateX', models.IntegerField(null=True)),
                ('coordinateY', models.IntegerField(null=True)),
                ('font', models.CharField(max_length=100, null=True)),
                ('font_size', models.IntegerField(null=True)),
                ('font_color', models.CharField(max_length=100, null=True)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.diary')),
            ],
            options={
                'db_table': 'Diary_Text',
            },
        ),
        migrations.CreateModel(
            name='DiaryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('imageX', models.IntegerField(null=True)),
                ('imageY', models.IntegerField(null=True)),
                ('diary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diary.diary')),
            ],
        ),
    ]
