# Generated by Django 3.2.7 on 2021-11-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='canvas',
            field=models.BinaryField(null=True),
        ),
    ]
