# Generated by Django 3.2.9 on 2021-12-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='diary',
            table='Diary',
        ),
        migrations.AlterModelTable(
            name='diaryhashtag',
            table='Diary_Hashtag',
        ),
        migrations.AlterModelTable(
            name='diaryimage',
            table='Diary_Image',
        ),
        migrations.AlterModelTable(
            name='handwriting',
            table='HandWriting',
        ),
    ]
