# Generated by Django 3.2.7 on 2021-10-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='diary',
            old_name='author',
            new_name='user',
        ),
    ]
