# Generated by Django 3.2.7 on 2021-10-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20211004_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.TextField()),
            ],
            options={
                'db_table': 'content',
            },
        ),
        migrations.RemoveField(
            model_name='diary',
            name='user',
        ),
    ]
