# Generated by Django 3.2.7 on 2021-11-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_diary_canvas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas', models.BinaryField(null=True)),
                ('date', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='diary',
            name='canvas',
        ),
    ]
