# Generated by Django 3.2.7 on 2021-10-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20211017_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='coordinateX',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='coordinateY',
            field=models.IntegerField(null=True),
        ),
    ]
