# Generated by Django 3.2.7 on 2021-11-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20211118_0035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Canvas',
        ),
        migrations.AddField(
            model_name='diary',
            name='canvas',
            field=models.BinaryField(null=True),
        ),
    ]
