# Generated by Django 3.2.7 on 2021-11-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20211118_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryimage',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='diaryimage',
            name='imageX',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='diaryimage',
            name='imageY',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='diaryimage',
            name='width',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='diarytext',
            name='coordinateX',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='diarytext',
            name='coordinateY',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='diarytext',
            name='font_size',
            field=models.FloatField(null=True),
        ),
    ]
