# Generated by Django 3.2.7 on 2021-10-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20211017_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='font',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
