# Generated by Django 3.2.7 on 2021-10-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_content_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='fontColor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='fontSize',
            field=models.IntegerField(null=True),
        ),
    ]
