# Generated by Django 3.2.9 on 2021-11-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20211130_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandWriting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hand_writing/')),
            ],
        ),
    ]
