# Generated by Django 3.2.7 on 2021-10-27 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20211019_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name', models.CharField(max_length=100, null=True)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('x', models.IntegerField(null=True)),
                ('y', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiaryText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('coordinateX', models.IntegerField(null=True)),
                ('coordinateY', models.IntegerField(null=True)),
                ('font', models.CharField(max_length=100, null=True)),
                ('font_size', models.IntegerField(null=True)),
                ('font_color', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'Diary_Text',
            },
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='content',
        ),
        migrations.AlterField(
            model_name='diary',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='diarytext',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.diary'),
        ),
        migrations.AddField(
            model_name='diaryimage',
            name='diary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diary.diary'),
        ),
    ]
