# Generated by Django 3.2.7 on 2021-10-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_auto_20211027_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryimage',
            name='name',
        ),
    ]
