# Generated by Django 3.2.7 on 2021-10-27 17:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_remove_diaryimage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryimage',
            name='height',
        ),
        migrations.RemoveField(
            model_name='diaryimage',
            name='width',
        ),
        migrations.RemoveField(
            model_name='diaryimage',
            name='x',
        ),
        migrations.RemoveField(
            model_name='diaryimage',
            name='y',
        ),
        migrations.AddField(
            model_name='diaryimage',
            name='attributes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None),
        ),
    ]
