# Generated by Django 3.2.7 on 2021-10-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_auto_20211028_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryimage',
            name='attributes',
            field=models.TextField(null=True),
        ),
    ]
