# Generated by Django 3.2.7 on 2021-11-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_alter_diaryimage_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryimage',
            name='attributes',
        ),
        migrations.AddField(
            model_name='diaryimage',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='diaryimage',
            name='imageX',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='diaryimage',
            name='imageY',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='diaryimage',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
