# Generated by Django 3.2.7 on 2021-11-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_auto_20211101_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='title',
        ),
        migrations.AddField(
            model_name='diary',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
